#request
uint8 payload_index 1       # see enum E_DjiMountPosition in dji_typedef.h
uint8 stream_source         # 1 = WIDE_CAM, 2 = ZOOM_CAM (E_DjiCameraManagerStreamSource)

---
#response
bool success
